### ISSUE TITLE
ZTF Catalog of Periodic Variable Stars

### ISSUE THREAD

**Issue by pruzhinskaya** [snad-space/ztf-viewer#12]
To add ZTF Catalog of Periodic Variable Stars 

http://variables.cn:88/ztf/

**Comment by hombit** [comment]
Repository with API was created
https://github.com/snad-space/ztf-periodic-catalog-db

Next step is updating the viewer

**Comment by hombit** [comment]
I haven't included candidates (aka Table6) to search results. Please, reopen the issue or put new if it is required
