### ISSUE TITLE
Fink link is not working

### ISSUE THREAD

**Issue by mayamolodec** [snad-space/ztf-viewer#129]
The link on Fink in Summary doesn't work. For example: https://ztf.snad.space/dr8/view/795102100003237
If you click on Alerce or Simbad it's working, but if you click on Fink nothing will happen.

![-215663_temp](https://user-images.githubusercontent.com/21056935/166230676-e799e4b0-6b5c-48b5-b49d-a24546438ec2.jpg)

**Comment by hombit** [comment]
Nice catch! The fix is merged, it will be a part of the next release. For now you could check development site https://master.ztf.snad.space/dr8/view/795102100003237
