### ISSUE TITLE
Transient name server

### ISSUE THREAD

**Issue by pruzhinskaya** [snad-space/ztf-viewer#13]
to add TNS
https://wis-tns.weizmann.ac.il/content/tns-getting-started
https://wis-tns.weizmann.ac.il/sites/default/files/api/TNS_APIs_manual.pdf

**Comment by hombit** [comment]
I'm not sure that they give us API key, but I have to try

**Comment by hombit** [comment]
Please, if you need photometric or spectral information on TNS table, put an issue or reopen this one
