### ISSUE TITLE
Astrocats

### ISSUE THREAD

**Issue by pruzhinskaya** [snad-space/ztf-viewer#14]
To add all astrocats

(https://astrocats.space/, API: https://github.com/astrocatalogs/OACAPI)

**Comment by hombit** [comment]
Do we really need all API calls or https://api.astrocats.space/ will be enough?

**Comment by hombit** [comment]
I haven't found a way to determine which catalog includes the source, so I added links to all of them

**Comment by pruzhinskaya** [comment]
I like it as it is now.
