### ISSUE TITLE
JS9 could not preload image

### ISSUE THREAD

**Issue by anlava** [snad-space/ztf-viewer#149]
JS9 doesn't display some FITS files and throws this issue:

> JS9 ERROR: could not preload image(s):  https://fits.ztf.snad.space/products/sci/2018/0621/355000/ztf_20180621355000_000685_zr_c05_o_q4_sciimg.fits

Example light curve: https://ztf.snad.space/dr8/view/685205400141854 (the brightest point in the flare)

**Comment by hombit** [comment]
I cannot reproduce it, I hope it was a temporal issue. Please free to reopen if you find more examples
