### ISSUE TITLE
Stamp classification is absent

### ISSUE THREAD

**Issue by pruzhinskaya** [snad-space/ztf-viewer#223]
Alerce Stamp classification exists but absent in the tables

Ex.: 717105400005221 or 789313400012360

It's not always like that (Ex.: 796115400009292), my guess is that it is shown only if both Stamp and LC_classifier exist in Alerce; if only Stamp... it is not shown for some reason.

**Comment by hombit** [comment]
Thank you for this, it should be fixed at https://pr219.ztf.snad.space/dr8/view/717105400005221
