### ISSUE TITLE
Design issues

### ISSUE THREAD

**Issue by hombit** [snad-space/ztf-viewer#30]
Add project description, how to cite, etc

**Comment by emilleishida** [comment]
I added some configuration wish list in [this document.](https://docs.google.com/document/d/1z4meCDQpmg1reas6YGncIgPdSpBY_hp8mpPbBzNwYic/edit?usp=sharing)

let me know if anything is unclear. 
these are obviously only guidelines for improve readability, but are not essential.

**Comment by hombit** [comment]
I renamed this issue because now it is about the whole site

**Comment by emilleishida** [comment]
I put comments about the General Catalog of variable stars but that is an example. 
the same design structure, if possible, should be repeated for the other cross-match possibilities.

**Comment by hombit** [comment]
I think we should close it now. Feel free to reopen or open new specific issues
