### ISSUE TITLE
Add some copyright to downloadable figures

### ISSUE THREAD

**Issue by hombit** [snad-space/ztf-viewer#31]
@emilleishida Please, give me some text and say a position where to write it

**Comment by emilleishida** [comment]
The text should go in the bottom of the figure, in italic, small font, light grey:

If possible to add date:

_Generated with the SNAD ZTF viewer on XX/XX/20XX_

If not possible to add date:

_Generated with the SNAD ZTF viewer_

**Comment by emilleishida** [comment]
PS: I would be super happy if we can write SNAD with the mirrored N :)

**Comment by hombit** [comment]
It is live now, but requires additional query parameter `copyright=yes`. "И" instead of "N" is challenging for PDF, I haven't found solution yet
https://ztf.snad.space/dr3/figure/680113300005170?other_oid=680213300009232&other_oid=1722207400009164&format=png&copyright=yes
![680113300005170-24](https://user-images.githubusercontent.com/1784493/98984269-47e15e80-2522-11eb-83fa-45d0497b0ff6.png)

**Comment by hombit** [comment]
I've also found that regular looks better than italic

**Comment by emilleishida** [comment]
That is great, thanks!

if possible, can we add a little more space between the x-label and the copyright line?
like one blank line would be enough.

**Comment by hombit** [comment]
Is it ok?
![cr](https://user-images.githubusercontent.com/1784493/99236178-240a6b00-27f7-11eb-8b96-2c34287b664a.png)

**Comment by emilleishida** [comment]
that is good, thanks!

**Comment by hombit** [comment]
Print copyright by default

**Comment by hombit** [comment]
Copyright margin is broken in 761e7d8, don't know how to fix it and keep layout tight
![iTerm2 v0paTM](https://user-images.githubusercontent.com/1784493/99647011-7f379a00-2a51-11eb-8578-99d9ebc04e4e.png)

**Comment by hombit** [comment]
Now copyright is on by default using this tight layout from the last comment
