### ISSUE TITLE
missing fits

### ISSUE THREAD

**Issue by alinusss** [snad-space/ztf-viewer#336]
while inspecting light curves, I click on some point after 1600 days and get error 
![image](https://github.com/snad-space/ztf-viewer/assets/39903826/134860f5-0c74-4b8e-bc39-be76c5c0fcb9)

**Comment by hombit** [comment]
It looks like the data is missed from IRSA IPAC, this folder is empty for me right now
https://irsa.ipac.caltech.edu/ibe/data/ztf/products/sci/2022/1217

**Comment by alinusss** [comment]
this error appears not for all objects - https://ztf.snad.space/view/644212300005848 this one works properly

**Comment by hombit** [comment]
It works again, closing it because we can do nothing with it
