### ISSUE TITLE
MPChecker cross-match

### ISSUE THREAD

**Issue by alinusss** [snad-space/ztf-viewer#337]
It would be great to add to the viewer a cross-match with minor planets and other Solar System stuff.

**Comment by hombit** [comment]
We need a Python prototype code for this.

**Comment by hombit** [comment]
We also can use [astcheck](https://www.projectpluto.com/astcheck.htm). However [`astorb.dat`](https://asteroid.lowell.edu/astorb/) should not used for data for older than 50 days

**Comment by hombit** [comment]
Could be relevant:
https://b612foundation.org/press-release-asteroid-institute-unveils-rapid-online-precovery-tool-for-searching-multiple-astronomical-datasets-in-minutes/

**Comment by hombit** [comment]
See implementation here:
https://github.com/snad-space/MPChecker
