### ISSUE TITLE
Gaia distances

### ISSUE THREAD

**Issue by pruzhinskaya** [snad-space/ztf-viewer#35]
_Gaia DR2 Distances_ rename in _Gaia DR2_.
- Keep the results from Bailer-Jones+, 2018 (Gaia DR2) as it is now + add as the last column the reference to Bailer-Jones+, 2018
- Add as a next row/rows - with bigskip from Bailer-Jones+ results - the cross-match with Gaia DR2 (Gaia Collaboration, 2018, 10.1051/0004-6361/201833051). Extract from there 

parallax, 
parallax_error, 
pmra, 
pmra_error, 
pmdec, 
pmdec_error, 
radius_val,
radius_percentile_lower,
radius_percentile_upper,
lum_val,
lum_percentile_lower,
lum_percentile_upper.

Add reference to  Gaia DR2+, 2018 as a last column.

Thanks!

**Comment by hombit** [comment]
Do you meen [I/345](https://vizier.u-strasbg.fr/viz-bin/VizieR?-source=I/345) Vizier catalog?

BTW, looks like too many columns for one table.

**Comment by pruzhinskaya** [comment]
Yes, I mean this catalog. 
We can put the estimations of physical parameters (radius_val,radius_percentile_lower,radius_percentile_upper,
lum_val,lum_percentile_lower,lum_percentile_upper) in a separate row.

**Comment by hombit** [comment]
We have parallax from DR3 and distances from Bailer-Jones' EDR3. Please open new issue if we need to actualize this issue after (E)DR3 releases
