### ISSUE TITLE
Migration of the TNS to cloud environment

### ISSUE THREAD

**Issue by pruzhinskaya** [snad-space/ztf-viewer#36]
The migration is planned to take place on Sun, Dec 6th 2020, around 08:00 UT.

The new URL of the TNS will be: https://www.wis-tns.org
Please make sure to be prepared for updating this base URL in all your scripts and links to the TNS.

The URL of the sandbox will be changed to: https://sandbox.wis-tns.org

**Comment by hombit** [comment]
Dear Bot/Group owners (sorry for having received this message multiple times).

The migration of the TNS to the AWS will take place on Sunday, Dec 27th at 08:00 UT (and NOT on Dec 6th as was previously mentioned).
We expect a downtime of up to 2 hrs, between 08:00 and 10:00 UT.

As mentioned, the new URL of the TNS will be: https://www.wis-tns.org; and the sandbox: https://sandbox.wis-tns.org

A redirect to the new URLs will be in place right after the migration, but please verify that your scripts respond well to following 301-Redirects (whether using curl, python's requests etc...); and ultimately update the new URLs.


An email will be sent to all immediately after the completion of the migration.
