### ISSUE TITLE
Friendly colors for figures

### ISSUE THREAD

**Issue by hombit** [snad-space/ztf-viewer#37]
Where possible, please ensure that your figures are colour-blind friendly. The use of red and green in the same figure is particularly problematic for some readers.

**Comment by hombit** [comment]
Colors are set here:
https://github.com/snad-space/ztf-viewer/blob/44e8273362d3e289051479026315d990a2d08250/util.py#L16

**Comment by pruzhinskaya** [comment]
Variants.
All the colours are distinguishable.

red1 - #CC3344
red2 - #D55B18
green1 - #66E490
green2 - #B5E466
blue - #2F64EA

<img width="382" alt="изображение" src="https://user-images.githubusercontent.com/16917953/105382405-16bb9380-5c21-11eb-89ce-c2d8d29e538a.png">


<img width="545" alt="изображение" src="https://user-images.githubusercontent.com/16917953/105382223-e542c800-5c20-11eb-9216-f4dedd089309.png">

<img width="547" alt="изображение" src="https://user-images.githubusercontent.com/16917953/105382272-effd5d00-5c20-11eb-8e28-6a60b3201516.png">

**Comment by hombit** [comment]
I played with it on https://www.color-blindness.com and found that red2 #D55B18 and green1 #66E490 is the best red-green pair. I prefer not to use blue because green and red are more idiomatic for _gr_
