### ISSUE TITLE
add ATLAS catalog

### ISSUE THREAD

**Issue by pruzhinskaya** [snad-space/ztf-viewer#5]
To add ATLAS catalog to the webpage. 

Vizier: http://vizier.u-strasbg.fr/viz-bin/VizieR?-source=J/AJ/156/241

A first catalog of variable stars measured by ATLAS (Heinze+, 2018)
https://ui.adsabs.harvard.edu/abs/2018AJ....156..241H/abstract

**Comment by hombit** [comment]
Do you know, is there any website with object light curves?
