### ISSUE TITLE
Fix FITS picking

### ISSUE THREAD

**Issue by hombit** [snad-space/ztf-viewer#57]
Sometimes a wrong FITS files is shown

**Comment by alinusss** [comment]
![image](https://user-images.githubusercontent.com/39903826/124595949-56420900-de6a-11eb-8baa-463b7525bd9c.png)
https://ztf.snad.space/products/sci/2019/0208/340613/ztf_20190208340613_000518_zr_c01_o_q1_sciimg.fits

example of a fits header - there's a field HJD there

**Comment by alinusss** [comment]
It would be nice to have zoom buttons in FITS viewer

**Comment by alinusss** [comment]
Error in fits loading
https://ztf.snad.space/dr4/view/682105100012889
data point mjd 1018.26468

**Comment by hombit** [comment]
```
JS9 ERROR: could not find /products/sci/2020/0618/261214/ztf_20200618261214_000682_zr_c05_o_q1_sciimg.fits
```

![image](https://user-images.githubusercontent.com/1784493/124762112-3595b400-df3b-11eb-907f-79c57d4163bb.png)

**Comment by hombit** [comment]
This bug is something non-related and it is fixed now

**Comment by hombit** [comment]
Closing for now, feel free to reopen
