### ISSUE TITLE
Reimplemt Fink support

### ISSUE THREAD

**Issue by hombit** [snad-space/ztf-viewer#70]
https://github.com/astrolabsoftware/fink-science-portal/pull/213

**Comment by JulienPeloton** [comment]
He he you were faster than me on this ;-) So basically this should work:

```
https://fink-portal.org/?query_type=Conesearch&ra=193.822&dec=2.89732&radius=5&startdate_conesearch=2021-07-01 05:59:36&window_days_conesearch=1
```

See https://fink-broker.org/2021-09-27-science-portal-updates/ for more information

**Comment by hombit** [comment]
@JulienPeloton thank you!
