### ISSUE TITLE
Adding The Sloan Digital Sky Survey Quasar Catalog: DR16

### ISSUE THREAD

**Issue by pruzhinskaya** [snad-space/ztf-viewer#72]
[Catalog ](https://ui.adsabs.harvard.edu/abs/2020ApJS..250....8L/abstract) contains two tables: a "superset" of all SDSS-IV/eBOSS objects targeted as quasars containing 1,440,615 observations and a quasar-only catalog containing 750,414 quasars.

We need a superset only which is here:
https://vizier.iucaa.in/viz-bin/VizieR-3?-source=VII/289/superset

Needed columns:

SDSS – SDSS-DR16 designation (HHMMSS.ss+DDMMSS.s; J2000) (SDSS_NAME) (meta.id;meta.main) 

RAJ2000 – Right Ascension (J2000) (RA) (pos.eq.ra;meta.main)

DEJ2000 – [-17.53/84.44] Declination (J2000) (DEC) (pos.eq.dec;meta.main)

Class – [0/50] Object classification from visual inspection (CLASS_PERSON) (Note 2)   (meta.code.class;src.class)

QSO – Flag indicating quasars included in final catalog (1=QSO; 2=questionable – see Section 3.6) (IS_QSO_FINAL) (meta.code) 

z – [-0.012/7.06] Best available redshift (src.redshift;pos.heliocentric)

r_z – Source for redshift z (SOURCE_Z)  (Note 3)   (meta.ref;pos.frame)

gmag – [13.3/30.1] PSF (AB) magnitude in g band (not corrected for Galactic extinction) (PSFMAGg) (phot.mag;em.opt.B)

rmag – [13.3/29.8] PSF (AB) magnitude in r band (not corrected for Galactic extinction) (PSFMAGr) (phot.mag;em.opt.R)

imag – [13.5/30] PSF (AB) magnitude in i band (not corrected for Galactic extinction) (PSFMAGi) (phot.mag;em.opt.I)

**Comment by pruzhinskaya** [comment]
Please, add sorting in radius search

<img width="131" alt="изображение" src="https://user-images.githubusercontent.com/16917953/161086879-5d6a558d-bfb2-4b1e-a882-8a41f3b4fc09.png">

**Comment by pruzhinskaya** [comment]
Please, add sorting in radius search

<img width="121" alt="изображение" src="https://user-images.githubusercontent.com/16917953/161087192-2817a936-1858-4fff-a30e-690f16c03f52.png">

**Comment by hombit** [comment]
Will be done as a part of #92
